### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by ir1979** [mikegashler/waffles#45]
I use VS 2013. After trying to build it shows: 

Error	1	error C1083: Cannot open source file: 'GAssociative.cpp': No such file or directory	C:\Program Files\waffles\src\GClasses\c1xx	GClasses

So the compiler can not create "gclasses.lib".  Where can I fid the file?

**Comment by mikegashler** [comment]
That file was removed some time ago. It looks like I neglected to also remove it from the VS project file. It should be fixed now. Thanks for letting me know there was a problem.

**Comment by oshapio** [comment]
Hey,
even though the fix was made, I'm still getting the same (including some more):
`Error	1	error C1083: Cannot open source file: 'GActivation.cpp': No such file or directory	
\waffles-master\src\GClasses\c1xx	GClasses

Error	2	error C1083: Cannot open source file: 'GBlock.cpp': No such file or directory	\waffles-master\src\GClasses\c1xx	GClasses

Error	5	error C1083: Cannot open source file: 'GNeuralDecomposition.cpp': No such file or directory	\waffles-master\src\GClasses\c1xx	GClasses

`

I'm using VS 2013 on Windows 10
