### ISSUE TITLE
'maybe-uninitialized' warning for prog variable in GHttp.cpp

### ISSUE THREAD

**Issue by zsurnz** [mikegashler/waffles#46]
I just tried to compile the most recent wafffles code from GitHub, using 'make opt' in the source directory without any option, on a newly installed Manjaro Linux. GHttp.cpp raises the 'maybe-uninitialized' warning:

GHttp.cpp: Dans la fonction membre « unsigned char* GClasses::GHttpClient::get(const char*, size_t*, unsigned int, unsigned int) »:
GHttp.cpp:575:6: error: « prog » pourrait être utilisé sans être initialisé dans cette fonction [-Werror=maybe-uninitialized]
      if(prog > prevProg)
      ^~
cc1plus : tous les avertissements sont traités comme des erreurs

**Comment by mikegashler** [comment]
Thank you! I believe it is fixed now.

**Comment by zsurnz** [comment]
Thank you! This solves the above issue. However I still get errors in GNeuralNet.h with the compiler (gcc-7.3.0) complaining that tanh, log, exp... are not members of 'std' (error msg below). Including <cmath> as suggested there:
https://stackoverflow.com/questions/16518210/sqrt-is-not-a-member-of-std?rq=1
is successful as a workaround.

In file included from GLearner.cpp:34:0:
GNeuralNet.h: In member function 'virtual double GClasses::GBlockTanh::eval(double) const':
GNeuralNet.h:283:61: error: 'tanh' is not a member of 'std'
  virtual double eval(double x) const override { return std::tanh(x); }
                                                             ^~~~
